# Generated by Django 6.0.6 on 2026-06-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("DINE_IN", "Dine-In"),
                    ("TAKEAWAY", "Takeaway"),
                    ("ROOM_SERVICE", "Room Service"),
                ],
                default="DINE_IN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="restaurant.table",
            ),
        ),
    ]
